### ISSUE TITLE
Migration Loris -> Cantaloupe

### ISSUE THREAD

**Issue by EmanuelaBoros** [impresso/impresso-middle-layer#532]
A new IIIF image server has been setup (with Cantaloupe - before it was Loris) and it has two layers of security:

- a proxy that filters whitelisted IPs for the project’s institutions (UniLU, UZH) - :white_check_mark:
- authentication at Cantaloupe level - a Pegasus link with the user and the password will arrive by email today (7th of March 2025)  :white_check_mark: This is the only authentication needed in the middle layer. Mail sent (burn after reading).

The image servers are presented [here](https://github.com/impresso/impresso-infrastructure/tree/main/servers/image-server): 
- Previous deprecated [Loris](https://github.com/impresso/impresso-infrastructure/tree/main/servers/image-server#loris)
- Newly installed [Cantaloupe](https://github.com/impresso/impresso-infrastructure/tree/main/servers/image-server#cantaloupe)

Changes to be taken in consideration:
- the request was before towards `dhlabsrv17.epfl.ch/iiif_impresso`, it is `iiif-impresso.epfl.ch/iiif/3/` (where `3` is the version of IIIF)
- example: `https://dhlabsrv17.epfl.ch/iiif_impresso/GDL-1998-01-05-a-p0008/full/max/!180/default.jpg` becomes `https://iiif-impresso.epfl.ch/iiif/3/GDL-1998-01-05-a-p0008/full/max/!180/default.jpg`

**Comment by theorm** [comment]
https://dev.impresso-project.ch/app has been updated to use Cantaloupe. Production will be updated with the next release. I'm keeping this issue open until production is updated.

**Comment by simon-clematide** [comment]
Some images are missing. I collected some of them while working on the bounding box issues. s3://41-processed-data-staging/bboxqa/bboxqa_v1-0-2__AGGREGATED_iiif-errors.jsonl.gz. But the specific file was not there.

**Comment by EmanuelaBoros** [comment]
I assume this was solved on your side:

https://dev.impresso-project.ch/api/proxy/iiif/FedGazDe-1907-12-18-a-p0014/287,153,1179,948/full/0/default.png
<img width="389" alt="Image" src="https://github.com/user-attachments/assets/f7cefeb3-ebdb-4bd5-b78c-0f808f5224bb" />

https://impresso-project.ch/api/proxy/iiif/FedGazDe-1907-12-18-a-p0014/287,153,1179,948/full/0/default.png


<img width="1106" alt="Image" src="https://github.com/user-attachments/assets/482b1080-0d31-43ef-aa9a-9cb08bbd0895" />

**Comment by theorm** [comment]
@EmanuelaBoros no it hasn't been solved on our side. The link referenced in my last message still shows a broken image:

https://dev.impresso-project.ch/app/issue/FedGazDe-1907-12-18-a/view?sq=&articleId=i0002&p=13&text=1

To see the error you need to look at the request in the network tab of the browser dev tools. Development environment has the new authorisation layer no present in production, that's why you would get an error trying to open the proxied image directly in the browser (that's likely where the oh-ho page comes from).

**Comment by EmanuelaBoros** [comment]
I checked the logs of Cantaloupe and it seems that the requests specifically for https://dev.impresso-project.ch/app/issue/FedGazDe-1907-12-18-a/view?sq=&articleId=i0002&p=13&text=1 do not arrive. I can see, for example, https://dev.impresso-project.ch/api/proxy/iiif/GDL-1998-01-05-a-p0008/full/max/!180/default.jpg.

**Comment by theorm** [comment]
I can't provide a deep link because of the authentication, but here is an example:

Request:
```
GET https://dev.impresso-project.ch/api/proxy/iiif/FedGazDe-1907-12-18-a-p0022/268,176,1175,1069/full/0/default.png
```

Response:
```
400 Bad Request

Invalid size


edu.illinois.library.cantaloupe.resource.IllegalClientArgumentException: Invalid size
	at edu.illinois.library.cantaloupe.resource.iiif.v3.Size.fromURI(Size.java:110)
	at edu.illinois.library.cantaloupe.resource.iiif.v3.Parameters.&#60;init&#62;(Parameters.java:96)
	at edu.illinois.library.cantaloupe.resource.iiif.v3.ImageResource.doGET(ImageResource.java:69)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:97)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:35)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:1583)


```

Hope this helps

**Comment by EmanuelaBoros** [comment]
Hello @theorm, on my side, this https://iiif-impresso.epfl.ch/iiif/2/FedGazDe-1907-12-18-a-p0014/287,153,1179,948/full/0/default.jpg works.

GET https://dev.impresso-project.ch/api/proxy/iiif/FedGazDe-1907-12-18-a-p0022/268,176,1175,1069/full/0/default.png 
this doesn't arrive in our logs..

**Comment by theorm** [comment]
I don't really know how else I can help detecting the source of the problem.
I double checked the configuration, the proxy forwards requests to `https://iiif-impresso.epfl.ch/iiif/3/`, which I assume means that the URL I referenced above is resolved to `https://iiif-impresso.epfl.ch/iiif/3/FedGazDe-1907-12-18-a-p0022/268,176,1175,1069/full/0/default.png`. Besides that the response body clearly hints that it is returned by a IIIF service version 3, which can only be cantaloupe (loris did not support v3 as far as I know). Is this possible that the logs do not include errors?

**Comment by EmanuelaBoros** [comment]
@theorm, thank you for the detail. It's because it solves to iiif/3/ and I was testing with iiif/2. 

https://iiif-impresso.epfl.ch/iiif/2/FedGazDe-1907-12-18-a-p0014/268,176,1175,1069/full/0/default.png --> works
https://iiif-impresso.epfl.ch/iiif/3/FedGazDe-1907-12-18-a-p0014/268,176,1175,1069/full/0/default.png --> does not work

I am looking into it.

**Comment by EmanuelaBoros** [comment]
@theorm, I think the syntax was wrong: "full" --> "max"

https://iiif-impresso.epfl.ch/iiif/3/FedGazDe-1907-12-18-a-p0014/268,176,1175,1069/full/0/default.png --> does not work
https://iiif-impresso.epfl.ch/iiif/3/FedGazDe-1907-12-18-a-p0014/268,176,1175,1069/max/0/default.png --> works

Other checks:
https://iiif-impresso.epfl.ch/iiif/2/FedGazDe-1907-12-18-a-p0014/full/full/0/default.png --> works, but it was the previous syntax
https://iiif-impresso.epfl.ch/iiif/3/FedGazDe-1907-12-18-a-p0014/full/full/0/default.png --> does not work for iiif3 --> change to: https://iiif-impresso.epfl.ch/iiif/3/FedGazDe-1907-12-18-a-p0014/full/max/0/default.png

**Comment by theorm** [comment]
Thank you @EmanuelaBoros . Do you know if using `max` will work with IIIF v2?

**Comment by EmanuelaBoros** [comment]
@theorm, it seems that yes. Do you have a fallback on iiif2?

**Comment by theorm** [comment]
@EmanuelaBoros still doesn't work. This and similar URLs still return the same error:

```
https://iiif-impresso.epfl.ch/iiif/3/FedGazDe-1907-12-18-a-p0014/max/30,/0/default.png
```

**Comment by theorm** [comment]
To add more confusion, this request returns an image:

```
https://iiif-impresso.epfl.ch/iiif/3/FedGazDe-1907-12-18-a-p0148/full/100,143/0/default.jpg
```

**Comment by theorm** [comment]
Now that I investigated it further I can see that some of the v3-incompatible URLs are stored in the Solr index. This means that even if we update the code to use `max` in the URLs we build, the URLs from Solr will not be affected. Unless there is a way to enable v2 compatibility in cantaloupe, we will need to rewrite all URLs sent to cantaloupe to be v3 compatible.

**Comment by EmanuelaBoros** [comment]
@theorm, v2 is already enabled in Cantaloupe.

**Comment by EmanuelaBoros** [comment]
Small refs for me:
* iif3 image specs: https://iiif.io/api/image/3.0/#4-image-requests
* iif2 image specs: https://iiif.io/api/image/2.0/#4-image-requests

Format:
- full/max/0/
- {region}/{size}/{rotation}

Changes in IIIF3:
* size in IIIF3 changed from "full" to "max"
* size has been restricted to `w,`, `,h`, `w,h`, `!w,h`, `pct:n`

FedGazDe-1907-12-18-a-p0014
* crashes in iiif3: https://iiif-impresso.epfl.ch/iiif/3/FedGazDe-1907-12-18-a-p0014/max/30,/0/default.png
* returns full images of size 30 in iiif2: https://iiif-impresso.epfl.ch/iiif/2/FedGazDe-1907-12-18-a-p0014/full/30,/0/default.png
* the correct iiif3: https://iiif-impresso.epfl.ch/iiif/3/FedGazDe-1907-12-18-a-p0014/full/30,/0/default.png (region cannot be "max")

FedGazDe-1907-12-18-a-p0148
* returns a small image which is correct: region=full, size=100,143, not rotated: https://iiif-impresso.epfl.ch/iiif/3/FedGazDe-1907-12-18-a-p0148/full/100,143/0/default.jpg

**Comment by theorm** [comment]
@EmanuelaBoros I ended up using [this library](https://www.npmjs.com/package/@iiif/parser) for migrating URLs to a v3 format before the requests are sent to Impresso IIIF server. My hope is that it would capture any other incompatibilities that may be there (even though the library could not handle some corner cases - I had to fix that).

For future reference, the `max` size value is supported in v2 alongside `full` (they both produce the same result). The `max` value is not available in v1, which means that original Impresso code was written for v1 and just happened to work with v2 by coincidence.
